---
- name: "run local"
  hosts: localhost
  connection: local
  tasks:
    - name: Brave get GPG keys
      ansible.builtin.get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg

    - name: Brave add repo
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
        state: present

    - name: install base GUI apps
      apt:
        name:
          - kde-standard
          - brave-browser
          - firefox
          - flatpak
          - terminator
          - sgt-puzzles
          - kdegames
        state: latest
    - name: Install multiple packages
      community.general.flatpak:
        name:
          - com.bitwarden.desktop
          - org.keepassxc.KeePassXC
